// From https://docs.google.com/spreadsheets/d/1e9tPQ0Fl61KkzEkCh3FIkUSUmXtxlpGPp0fMmTipxoM/edit#gid=0
export const clsAlgs = [
  ["(y) [R' D R: U']", "(y) [R' D R: U']", "⭐⭐⭐⭐", "Allows CP control."],
  ["(U) K' F' K U' h'", "(U) R U' R' F' R U R' U' l' U l", "", ""],
  ["(U') h U K' F K", "(U') l' U' l U R U' R' F R U R'", "", ""],
  [
    "(U') K' U2 (K U')2 K'",
    "(U') R U' R' U2 (R U R' U')2 R U' R'",
    "⭐⭐⭐⭐",
    "",
  ],
  ["(U') K' U' K2", "(U') R U' R' U' R U2 R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(U') h' U K' F' K",
    "(U') l' U l U R U' R' F' R U R'",
    "⭐⭐⭐⭐",
    "switch",
  ],
  [
    "K U K U' K' U2' K",
    "R U R' U R U R' U' R U' R' U2' R U R'",
    "⭐⭐⭐⭐",
    "",
  ],
  ["K2 U [R: K2 U' K']", "R U2 R' U [R: R U2 R' U' R U' R']", "⭐⭐", ""],
  [
    "(U') K' U2 (K' J2') U J'",
    "(U') R U' R' U2 (R U' R2' U2 R) U R' U R",
    "",
    "",
  ],
  ["K U' K' U2 K2", "R U R' U' R U' R' U2 R U2 R'", "⭐⭐⭐", ""],
  ["(y') U J2 U' J", "(y') U R' U2' R U' R' U' R", "⭐⭐⭐⭐", ""],
  ["(U) K' U h U K' F", "(U) R U' R' U l' U' l U R U' R' F", "", ""],
  ["(U) J U' J2 K2 U K", "(U) R' U' R U' R' U2' R2 U2 R' U R U R'", "", ""],
  [
    "(U') R2 U2' R' J U K2 U R'",
    "(U') R2 U2' R2' U' R U R U2 R' U R'",
    "⭐⭐⭐⭐",
    "really fast, but you have to grip correctly",
  ],
  ["K' J2 U J' K", "R U' R2' U2' R U R' U R2 U R'", "⭐", ""],
  ["K U' K' U K'", "R U R' U' R U' R' U R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["(y') U' J U2' J y", "(y') U' R' U' R U2' R' U' R y", "⭐⭐", ""],
  ["J' U' K' U2 K' J", "R' U R U' R U' R' U2 R U' R2' U' R", "⭐", ""],
  ["(U2) h U K' F U' K2", "(U2) l' U' l U R U' R' F U' R U2 R'", "⭐", ""],
  ["(U') K' U2 K'", "(U') R U' R' U2 R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["(U) K2 U' K U K", "(U) R U2 R' U' R U R' U R U R'", "⭐⭐", ""],
  ["(U2)' K' U2 K2 U2 K'", "(U2)' R U' R' U2 R U2 R' U2 R U' R'", "⭐⭐⭐", ""],
  ["R U' K2 U' K' R'", "R U' R U2 R' U' R U' R' R'", "⭐⭐⭐", ""],
  [
    "(U') (K' U2 K') (J U' J2')",
    "(U') (R U' R' U2 R U' R') (R' U' R U' R' U2 R)",
    "",
    "learn",
  ],
  ["K' U J U' J2 K'", "R U' R' U R' U' R U' R' U2' R2 U' R'", "⭐⭐", ""],
  [
    "(U2) K U2' (J U' J2) K",
    "(U2) R U R' U2' (R' U' R U' R' U2' R) R U R'",
    "⭐⭐",
    "switch",
  ],
  [
    "(U') K' U' K' U' h' U K' F'",
    "(U') R U' R' U' R U' R' U' l' U l U R U' R' F'",
    "⭐⭐",
    "switch",
  ],
  [
    "K' U' [R: U K2 U' K']",
    "R U' R' U' [R: U R U2 R' U' R U' R']",
    "⭐⭐⭐⭐",
    "",
  ],
  ["(U) R K U K2 U R'", "(U) R2 U R' U R U2 R' U R'", "⭐⭐⭐⭐", "10.00"],
  [
    "(U') (R U')2 (R' U)3 J",
    "(U') (R U')2 (R' U)3 R' U' R",
    "⭐⭐⭐",
    "learn; bunch of regrips, but very fun.",
  ],
  ["(U2) l (K' U)3 l'", "(U2) l (R U' R' U)3 l'", "⭐⭐⭐", ""],
  ["(U') K' U' J K' J2", "(U') R U' R' U' R' U' R2 U' R2' U2' R", "⭐⭐", ""],
  [
    "(U) K U' K2 U' K' U K ",
    "(U) R U R' U' R U2 R' U' R U' R' U R U R' ",
    "⭐⭐⭐",
    "switch",
  ],
  ["(U2) K J2' K J'", "(U2) R U R2' U2 R2 U R2' U R", "⭐⭐⭐⭐⭐", "learn"],
  ["(U') K' U2 K U' K'", "(U') R U' R' U2 R U R' U' R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["(U) K U K U' K2", "(U) R U R' U R U R' U' R U2 R'", "⭐⭐⭐⭐", ""],
  ["(U') K' U' K' U K2", "(U') R U' R' U' R U' R' U R U2 R'", "⭐⭐", ""],
  ["(U') [R' D' R: U]", "(U') [R' D' R: U]", "⭐⭐⭐⭐", "Allows CP control."],
  ["(U') K2 U K2 U K2", "(U') R U2 R' U R U2 R' U R U2 R'", "⭐⭐⭐⭐", ""],
  ["K2 h' U K' F' K2", "R U2 R' l' U l U R U' R' F' R U2 R'", "⭐⭐", ""],
  ["(U) F' K U' h' U' K", "(U) F' R U R' U' l' U l U' R U R'", "⭐⭐⭐", ""],
  ["(y' U) J' U J2", "(y' U) R' U R U R' U2' R", "⭐⭐⭐⭐", ""],
  ["[K U': h] F", "[R U R' U': l' U' l] F", "⭐⭐⭐", "learn"],
  ["(U) K2 U2 K U2 K2", "(U) R U2 R' U2 R U R' U2 R U2 R'", "⭐⭐⭐", ""],
  [
    "(U2) K U K' U' K' U K'",
    "(U2) R U R' U R U' R' U' R U' R' U R U' R'",
    "",
    "",
  ],
  ["(U2' ) K2 U K2 U2 K", "(U2' ) R U2 R' U R U2 R' U2 R U R'", "⭐⭐⭐", ""],
  ["K U2 F' K U' h'", "R U R' U2 F' R U R' U' l' U l", "⭐⭐⭐", ""],
  ["(U) K' U K U' K", "(U) R U' R' U R U R' U' R U R'", "⭐⭐⭐⭐", ""],
  ["(U') K2 U K", "(U') R U2 R' U R U R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(U2) K U [R: K2 U' K' U]",
    "(U2) R U R' U [R: R U2 R' U' R U' R' U]",
    "⭐⭐⭐⭐",
    "",
  ],
  [
    "(U2) K' J2 U J' U' K2",
    "(U2) R U' R2' U2' R U R' U R U' R U2 R'",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "R2 U R' U R U2 R2 U' R U' R' U2 R U R'",
    "R2 U R' U R U2 R2 U' R U' R' U2 R U R'",
    "",
    "learn",
  ],
  [
    "(K2 U' K') R2 U2 R2 U' R2 U' R2",
    "(R U2 R' U' R U' R') R2 U2 R2 U' R2 U' R2",
    "⭐⭐",
    "learn",
  ],
  [
    "R U' R U2 R2 U' R2 U' R' U R' U' R U R'",
    "R U' R U2 R2 U' R2 U' R' U R' U' R U R'",
    "⭐⭐",
    "learn",
  ],
  ["(U') K U' K' U' K", "(U') R U R' U' R U' R' U' R U R'", "⭐⭐⭐⭐", ""],
  ["(U) K U2' K", "(U) R U R' U2' R U R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(U) [R: U' K U K2] U' K'",
    "(U) [R: U' R U R' U R U2 R'] U' R U' R'",
    "⭐⭐",
    "",
  ],
  [
    "K' U2 R U' R U2' R2' U' R2 U' R2'",
    "R U' R' U2 R U' R U2' R2' U' R2 U' R2'",
    "⭐⭐",
    "",
  ],
  ["(y' U) J' U2' J'", "(y' U) R' U R U2' R' U R", "⭐⭐⭐⭐", ""],
  [
    "(U) (J2' U J') K' U' K2",
    "(U) (R' U2 R U R' U R) R U' R' U' R U2 R'",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "K' U' K' U' h U K' F",
    "R U' R' U' R U' R' U' l' U' l U R U' R' F",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "(U2) K J U' J2 K2",
    "(U2) R U R2' U' R U' R' U2' R2 U2 R'",
    "⭐⭐⭐",
    "learn",
  ],
  ["(U) K U2' K2 U K2", "(U) R U R' U2' R U2 R' U R U2 R'", "", ""],
  [
    "(U') K U2' K U' K U2' K",
    "(U') R U R' U2' R U R' U' R U R' U2' R U R'",
    "",
    "learn",
  ],
  [
    "J' U2 [R': J U2 J]",
    "R' U R U2 [R': R' U' R U2 R' U' R]",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "(U2) [R: U K U K2] U K2",
    "(U2) [R: U R U R' U R U2 R'] U R U2 R'",
    "⭐⭐",
    "learn",
  ],
  ["K U K' J2 K J'", "R U R' U R U' R2' U2' R2 U R2' U R", "⭐", ""],
  [
    "(U') K' U' K U K2 U K'",
    "(U') R U' R' U' R U R' U R U2 R' U R U' R'",
    "⭐",
    "",
  ],
  ["U K2 U2 K U K'", "U R U2 R' U2 R U R' U R U' R'", "⭐⭐⭐⭐", ""],
  ["(U2) K' U K' U' K", "(U2) R U' R' U R U' R' U' R U R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(U) K2 U' K2 U K2 U' K",
    "(U) R U2 R' U' R U2 R' U R U2 R' U' R U R'",
    "⭐⭐",
    "anti-Sune canceling into O00 ",
  ],
  [
    "(U') K' U' [R: K U K2]",
    "(U') R U' R' U' [R: R U R' U R U2 R']",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "(U) K U (K' U')2 K",
    "(U) R U R' U (R U' R' U')2 R U R'",
    "⭐⭐⭐",
    "learn",
  ],
  [
    "R' U R' U2 R2 U' R' U2 R U' R2 U2 R2",
    "R' U R' U2 R2 U' R' U2 R U' R2 U2 R2",
    "",
    "",
  ],
  [
    "R' U2 R U2 R U' R' U' R' U R2 U R'",
    "R' U2 R U2 R U' R' U' R' U R2 U R'",
    "",
    "awkward U push at end",
  ],
  ["(U') K2 U K' U' K'", "(U') R U2 R' U R U' R' U' R U' R'", "⭐⭐⭐⭐", ""],
  ["(U2) K' U2 K U K", "(U2) R U' R' U2 R U R' U R U R'", "⭐⭐⭐⭐", ""],
  [
    "(U2) K' J2 U J' U2 K'",
    "(U2) R U' R2' U2' R U R' U R U2 R U' R'",
    "⭐⭐⭐",
    "learn",
  ],
  ["(U') K2 U K J U' J2'", "(U') R U2 R' U R U R2' U' R U' R' U2 R", "", ""],
  ["(U') K' U K2 U' K", "(U') R U' R' U R U2 R' U' R U R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(sledge)3",
    "(R' F R F')3",
    "",
    "use instead of the other alg for corner control",
  ],
  ["(U2) K2 U2 K' U2 K2", "(U2) R U2 R' U2 R U' R' U2 R U2 R'", "⭐⭐⭐", ""],
  [
    "(U') K U' K U K U' K'",
    "(U') R U R' U' R U R' U R U R' U' R U' R'",
    "",
    "",
  ],
  [
    "(U2) R U2 R U2 R2 U' R2 U' R' U R'",
    "(U2) R U2 R U2 R2 U' R2 U' R' U R'",
    "⭐⭐⭐",
    "",
  ],
  [
    "U' K2 U [R: U' K U K2]",
    "U' R U2 R' U [R: U' R U R' U R U2 R']",
    "",
    "learn",
  ],
  [
    "U' J' U2 [R: K2 U2 K] U R'",
    "U' R' U R U2 [R: R U2 R' U2 R U R'] U R'",
    "",
    "learn?",
  ],
  [
    "K U [R: U' K U K2 U']",
    "R U R' U [R: U' R U R' U R U2 R' U']",
    "",
    "learn?",
  ],
  ["(U2) K' U K U K'", "(U2) R U' R' U R U R' U R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["K' (J U' J2') K", "R U' R' (R' U' R U' R' U2 R) R U R'", "", "learn"],
  ["U K U' K2 U K' ", "U R U R' U' R U2 R' U R U' R' ", "⭐⭐⭐", ""],
  [
    "(U2) K' F K U' h",
    "(U2) R U' R' F R U R' U' l' U' l",
    "⭐⭐⭐⭐⭐",
    "switch",
  ],
  ["(K U')3", "(R U R' U')3", "⭐⭐⭐⭐", ""],
  ["(U2) K' U' K' U2 K", "(U2) R U' R' U' R U' R' U2 R U R'", "⭐⭐⭐⭐", ""],
  ["(U) K2 U' K2 U' K2", "(U) R U2 R' U' R U2 R' U' R U2 R'", "⭐⭐⭐", ""],
  ["(U') J K' J2 K'", "(U') R' U' R2 U' R2' U2' R2 U' R'", "⭐⭐⭐⭐", "learn"],
  ["(U') K U K' U2 K", "(U') R U R' U R U' R' U2 R U R'", "⭐⭐⭐⭐", ""],
  [
    "(U) J' U' [R': J K2 J U']",
    "(U) R' U R U' [R': R' U' R2 U2 R2' U' R U']",
    "⭐⭐⭐",
    "",
  ],
  [
    "(U') K' U' K U' K U2 K'",
    "(U') R U' R' U' R U R' U' R U R' U2 R U' R'",
    "",
    "learn",
  ],
  ["L' R2 U R2 U' L U2 R2 U2 R2", "L' R2 U R2 U' L U2 R2 U2 R2", "⭐", ""],
  [
    "(U) [R: U2 K U K2' U] U2' K",
    "(U) [R: U2 R U R' U R U2' R' U] U2' R U R'",
    "⭐",
    "",
  ],
  [
    "(U2) [R': J2' U' K' U2] U R2 U' R2",
    "(U2) [R': R' U2 R U' R U' R' U2] U R2 U' R2",
    "",
    "learn",
  ],
  ["(U2) [F': K U K2]", "(U2) [F': R U R' U R U2 R']", "⭐⭐⭐", ""],
  ["(U2) R' U R (U' R)3 (U R')2", "(U2) R' U R (U' R)3 (U R')2", "", "learn"],
  [
    "(U2) R2 U2 R U' R2 U R2 U' R U' R2",
    "(U2) R2 U2 R U' R2 U R2 U' R U' R2",
    "",
    "learn",
  ],
  ["(U2) K2 U2 K' U K'", "(U2) R U2 R' U2 R U' R' U R U' R'", "⭐⭐⭐", ""],
  [
    "K2 U' [R: K2 U' K' U']",
    "R U2 R' U' [R: R U2 R' U' R U' R' U']",
    "⭐⭐",
    "learn",
  ],
  [
    "(K2 U' K') U (K' U' K2)",
    "(R U2 R' U' R U' R') U (R U' R' U' R U2 R')",
    "⭐⭐",
    "learn",
  ],
  [
    "(U') K2 U2 K2 U K'",
    "(U') R U2 R' U2 R U2 R' U R U' R'",
    "⭐⭐⭐",
    "switch",
  ],
  [
    "(U2) K' U K U K U' K'",
    "(U2) R U' R' U R U R' U R U R' U' R U' R'",
    "⭐⭐⭐",
    "",
  ],
  [
    "(U) J2 K J' U K",
    "(U) R' U2' R2 U R2' U R U R U R'",
    "⭐⭐⭐⭐⭐",
    "learn",
  ],
  [
    "(U) K U' K2 U K U' K'",
    "(U) R U R' U' R U2 R' U R U R' U' R U' R'",
    "",
    "",
  ],
  ["(U') K U' K U K'", "(U') R U R' U' R U R' U R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["(U) K U' K2 U2 K2", "(U) R U R' U' R U2 R' U2 R U2 R'", "⭐⭐⭐", ""],
  ["K2 U J U' J2 K", "R U2 R' U R' U' R U' R' U2' R2 U R'", "", "learn"],
  ["(y') (J U)3", "(y') (R' U' R U)3", "", ""],
  [
    "(U') K' U2 [R: U' K2 U' K' U2']",
    "(U') R U' R' U2 [R: U' R U2 R' U' R U' R' U2']",
    "",
    "",
  ],
  ["(U) K2 U' K2 U2 K'", "(U) R U2 R' U' R U2 R' U2 R U' R'", "⭐⭐", ""],
  [
    "K' U2 K' U K' U2 K'",
    "R U' R' U2 R U' R' U R U' R' U2 R U' R'",
    "⭐⭐⭐",
    "learn",
  ],
  ["K U2' K2 U2 K", "R U R' U2' R U2 R' U2 R U R'", "⭐⭐", ""],
  [
    "J2' K' U2' J2' K J2",
    "R' U2 R2 U' R' U2' R' U2 R2 U R2' U2' R",
    "",
    "learn",
  ],
  [
    "R U2 R U R' U R U' R2 U R2 U2 R2",
    "R U2 R U R' U R U' R2 U R2 U2 R2",
    "",
    "learn",
  ],
  [
    "(U' ) K' U K2 U' K2 U K2",
    "(U' ) R U' R' U R U2 R' U' R U2 R' U R U2 R'",
    "⭐",
    "",
  ],
  ["(K U)2 K' U' K", "(R U R' U)2 R U' R' U' R U R'", "", "learn?"],
  [
    "(U') K (J2 U J') U' K",
    "(U') R U R' (R' U2' R U R' U R) U' R U R'",
    "",
    "learn",
  ],
  [
    "(U') (J2 U J') (K U2 K)",
    "(U') (R' U2' R U R' U R) (R U R' U2 R U R')",
    "",
    "learn",
  ],
  ["(U') K U' K U2' K2", "(U') R U R' U' R U R' U2' R U2 R'", "⭐⭐⭐", ""],
  [
    "J' U' (K J) K' U (J K)",
    "R' U R U' (R U R2' U' R) R U' R' U (R' U' R2 U R')",
    "",
    "",
  ],
  [
    "(U') K' U K' h U K' F",
    "(U') R U' R' U R U' R' l' U' l U R U' R' F",
    "⭐⭐⭐",
    "",
  ],
  [
    "(U2) K U [R: U2 K2 U' K' U2]",
    "(U2) R U R' U [R: U2 R U2 R' U' R U' R' U2]",
    "",
    "",
  ],
  ["R K2 U' K' U2 R'", "R2 U2 R' U' R U' R' U2 R'", "⭐⭐⭐", ""],
  ["K2 U2 K2 U' K", "R U2 R' U2 R U2 R' U' R U R'", "⭐⭐⭐", ""],
  ["K U' K2 U' K", "R U R' U' R U2 R' U' R U R'", "⭐⭐⭐", ""],
  ["K' U' K U' K2", "R U' R' U' R U R' U' R U2 R'", "⭐⭐⭐⭐", ""],
  [
    "(U') [R: K2 U' K'] U' K'",
    "(U') [R: R U2 R' U' R U' R'] U' R U' R'",
    "⭐⭐⭐",
    "learn",
  ],
  ["(U) [F': K U K' U K2]", "(U) [F': R U R' U R U' R' U R U2 R']", "⭐⭐", ""],
  [
    "(U') [R: U [R D: J2']] U2 K'",
    "(U') [R: U [R D: R' U2 R]] U2 R U' R'",
    "⭐⭐",
    "learn, really learn",
  ],
  ["(K' U2)3 K'", "(R U' R' U2)3 R U' R'", "", ""],
  ["U2 K U (K U')2 K2", "U2 R U R' U (R U R' U')2 R U2 R'", "", ""],
  ["U K2 U2 K' (U K)2", "U R U2 R' U2 R U' R' (U R U R')2", "", ""],
  ["(K2 U2' K U')2", "(R U2 R' U2' R U R' U')2", "⭐", ""],
  [
    "(K' J') U' K (J' K') U J",
    "(R U' R2' U R) U' R U R' (R' U R2 U' R') U R' U' R",
    "",
    "learn",
  ],
  [
    "(U') K2 U K2 U' K' U' K",
    "(U') R U2 R' U R U2 R' U' R U' R' U' R U R'",
    "",
    "learn",
  ],
  ["(U) K2 U K [R' D' R, U]", "(U) R U2 R' U R U R' [R' D' R, U]", "", "learn"],
  ["(U') [R: U2' K U K2]", "(U') [R: U2' R U R' U R U2 R']", "⭐⭐⭐⭐", ""],
  ["K' U K2 U2 K2", "R U' R' U R U2 R' U2 R U2 R'", "⭐⭐⭐", ""],
  ["K' U K2 U K'", "R U' R' U R U2 R' U R U' R'", "⭐⭐⭐⭐⭐", ""],
  [
    "(U) K U [R: K U K2]",
    "(U) R U R' U [R: R U R' U R U2 R']",
    "⭐⭐⭐⭐",
    "learn",
  ],
  [
    "(U) [F': K2 U' K U' K']",
    "(U) [F': R U2 R' U' R U R' U' R U' R']",
    "⭐⭐",
    "",
  ],
  ["K2 U K' U K", "R U2 R' U R U' R' U R U R'", "⭐⭐⭐⭐", ""],
  ["K2 (U K')2 U' K'", "R U2 R' (U R U' R')2 U' R U' R'", "⭐⭐", "learn"],
  ["(K2 U2 K' U)2", "(R U2 R' U2 R U' R' U)2", "⭐", ""],
  [
    "F' U F R U R' U' F R' F' R F' U' F",
    "F' U F R U R' U' F R' F' R F' U' F",
    "",
    "",
  ],
  ["(U K' U2 K2)2", "(U R U' R' U2 R U2 R')2", "⭐", "learn"],
  ["", "", "⭐⭐⭐⭐⭐", ""],
  ["K U K2", "R U R' U R U2 R'", "⭐⭐⭐⭐⭐", ""],
  ["K2 U' K'", "R U2 R' U' R U' R'", "⭐⭐⭐⭐⭐", ""],
  ["K U K' U K2", "R U R' U R U' R' U R U2 R'", "⭐⭐⭐⭐", ""],
  ["K U' h' U K' F'", "R U R' U' l' U l U R U' R' F'", "⭐⭐⭐⭐", ""],
  ["x' [R U' R', D] x", "x' [R U' R', D] x", "⭐⭐⭐⭐", ""],
  ["x' [R U R', D] x", "x' [R U R', D] x", "⭐⭐⭐⭐", ""],
  ["J U (J' U2)2 J", "R' U' R U (R' U R U2)2 R' U' R", "⭐⭐⭐", "learn"],
  ["R2 D R' U2 R D' R' U2 R'", "R2 D R' U2 R D' R' U2 R'", "⭐", ""],
  ["K2 J K' J2", "R U2 R2' U' R2 U' R2' U2' R", "⭐⭐⭐⭐", ""],
  // new alg (not on spreadsheet)
  ["", "R U' R' U2 R U2' R' U' R U2' R'", "⭐⭐", ""],
];
